### ISSUE TITLE
Session keepalive bug (main branch)

### ISSUE THREAD

**Issue by thlehmann-ionos** [nextcloud/user_oidc#1009]
While trying to debug another issue (to be created) I tried the most recent version (138da66f2036d2a262fc5bc1db051d1f4327d282) on the main branch. I think I found a problem there.

I was just reading code and had the debugger attached and ran into the `logout()` method. This was approximately 5 min after login (my access token was only valid for 5 minutes).

Wondering what would trigger the logout I traced back the stack and found the recently introduced `TokenService`, which checks the expiry of the access token.
It was called by the `checkLoginToken()` hook installed by user_oidc's `Application`.
The request that caused this call was `/index.php/apps/files/api/v1/stats` (quota info checks).
This also affects uploads, which would break long running uploads across ID token validity.

## Network log

```
> GET /index.php/apps/files/api/v1/stats
< 302 Found
< Location: http://localhost:8080/index.php/apps/user_oidc/login/3?redirectUrl=/index.php/apps/files/api/v1/stats
```

## Token valiation

`user_oidc/lib/Service/TokenService.php`:

```
public function checkLoginToken(): void {
	// ...

	$token = $this->getToken();
	if ($token === null) {
		// ...
	} elseif ($token->isExpired()) {
		// We'll run into this branch, token validity was 300s (5m)
		// ...
		$this->reauthenticate($token->getProviderId());
	}
}

public function reauthenticate(int $providerId) {
	// Logout the user and redirect to the oidc login flow to gather a fresh token
	$this->userSession->logout();

	// ...
}
```

## Expectation / proposal

Refreshing the access token and only invalidating the Nextcloud session if that fails.

**Comment by julien-nc** [comment]
Thanks for reporting this issue!

I'm not sure what happens on your side because when executing `checkLoginToken`, the token is first obtained with `$this->getToken()` which tries to refresh it.

Could you reproduce the issue and check if you find lines that contain `[TokenService] Failed to refresh token` in nextcloud.log?

**Comment by thlehmann-ionos** [comment]
Thank you for the quick response!

Sorry. I missed that `refreshExpiresIn` was zero for me. 

The refresh is fine now.

Keycloak is a configuration nightmare. I had to enable **Offline Session Max Limited** in the realm settings » Sessions tab » lower half of the config page.
