### ISSUE TITLE
Unable to enable the app

### ISSUE THREAD

**Issue by istvan-berenyi** [nextcloud/user_oidc#121]
OS; Centos 8
Nextcloud 20.1

Upon downloading the official OpenID app i'm unable to enable the app.
Error:

An error occured during the request. Unable to proceed.
Column name "oc_user_oidc"."display_name" is NotNull, but has empty string or null as default.

**Comment by aszlig** [comment]
Duplicate of #90.

**Comment by kesselb** [comment]
Duplicate of #90
