### ISSUE TITLE
Audience verification fails if audience is an array of values

### ISSUE THREAD

**Issue by coudot** [nextcloud/user_oidc#13]
The audience claim can be an array. In this case the check fails, even if audience is correct: https://github.com/nextcloud/user_oidc/blob/1048625950262f58415455790e9fcc94fbb3ffe9/lib/Controller/LoginController.php#L210

See OpenID Connect specification: https://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken
> The Client MUST validate that the aud (audience) Claim contains its client_id value registered at the Issuer identified by the iss (issuer) Claim as an audience. The aud (audience) Claim MAY contain an array with more than one element. The ID Token MUST be rejected if the ID Token does not list the Client as a valid audience, or if it contains additional audiences not trusted by the Client.

**Comment by rullzer** [comment]
@coudot o good catch.
I'll look into that.

**Comment by coudot** [comment]
You can see here a good way to solve this issue: https://github.com/Worteks/OpenID-Connect-PHP/blob/master/src/OpenIDConnectClient.php#L940

**Comment by rullzer** [comment]
thnx.
@coudot btw if you'd be interested PR's are always welcome

**Comment by coudot** [comment]
Yes, I will propose you one.

**Comment by coudot** [comment]
See #14
