### ISSUE TITLE
User accounts created after OIDC login do not show up in admin user list

### ISSUE THREAD

**Issue by timstoop** [nextcloud/user_oidc#222]
Hi,

I was able to log in using OIDC and that seems to work fine, even creates the account an everything. However, after I log out again, I noticed that the new user does not show up in the user list. This makes it impossible (as far as I can tell) to add users to specific groups and apply quotas. Is this intended behaviour or did I do something wrong?

**Comment by Steinhose444** [comment]
hey i have the same problem, have you found a solution for it yet?

**Comment by juliushaertl** [comment]
Duplicate of #7, implementation pending in #267
