### ISSUE TITLE
No user reference created after first login

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/user_oidc#299]
I have followed the instructions in @schiessle [article](https://www.schiessle.org/articles/2020/07/26/nextcloud-and-openid-connect/) today to setup Nextcloud OpenID sign-on on Keycloak.

I successfully logged in with a user defined in Keycloak, but I noticed that the a reference of the user has not created in Nextcloud.

This means that the user is not searchable in the share panel, for example.

I tried with [Social Login](https://github.com/zorn-v/nextcloud-social-login) OpenID, and the user reference was created as expected.

**Comment by schiessle** [comment]
This was just implemented recently and not yet released, right @juliushaertl 

reference: https://github.com/nextcloud/user_oidc/commit/e9dde693c9f5f2eae6d39245d066047157dd3ba2#diff-44618b6c8e4636b6373f44259f05a4c776a8d323524d939ec02a8af53896895f

**Comment by juliushaertl** [comment]
Yes, that was fixed by #267 New release is expected soonish.
