### ISSUE TITLE
"Update provider settings" is not usable to update settings

### ISSUE THREAD

**Issue by alerque** [nextcloud/user_oidc#310]
While setting up a provider, the settings screen works fine the first time. Thereafter when I select the edit icon next to a provider to open the "Update provider settings" dialog I am unable to save, it just throws an error saying a provider with the same name already exists. I was able to update the provider settings using `occ ocnfig:app:set user_oidc <key> --value <value>` and got my provider working after the initial incorrect data, but not using the web interface.

**Comment by pmarini-nc** [comment]
Hi @alerque , can you please check if the behaviour described here matches the one described in #307 ?

**Comment by alerque** [comment]
Yes it is. Not sure how I missed that having skimmed open issues. Distracted I guess.

Closing as duplicate.
