### ISSUE TITLE
Disabling other backends setting has no effect

### ISSUE THREAD

**Issue by alerque** [nextcloud/user_oidc#312]
The README claims:

> If there is only one OIDC provider configured, it can be made the default login method and the user would get redirected to the provider immediately for the login.

There doesn't appear to be any UI for this, but it also gives an `occ` command to set this up. I've run that command at it has no apparent affect, my login screen still has the default form + the new OIDC option. Note I've had a SAML arrangement with `user_saml` before that *did* work to take over as the sole authentication mechanism, but I have that app disabled right now. My authentication flow otherwise works as expected against Keycloak.

```console
$ occ config:list user_oidc
{
    "apps": {
        "user_oidc": {
            "allow_multiple_user_backends": "0",
            "enabled": "yes",
            "id4me_enabled": "0",
            "installed_version": "1.0.0",
            "provider-3-mappingUid": "preferred_username",
            "provider-3-uniqueUid": "0",
            "types": "authentication"
        }
    }
}
```

You can see the value got set (that key didn't exist before running the `occ` command) but isn't functional as advertised.

**Comment by juliushaertl** [comment]
Do you have multiple oidc providers setup or just one?

**Comment by juliushaertl** [comment]
Are you running 1.0.0? As https://github.com/nextcloud/user_oidc/pull/304 was not released yet, so that setting is only possible with the next version.

**Comment by alerque** [comment]
Yes I'm using 1.0.0 — and I jumped on it specifically because I saw some key issues closed and then the release. Sadly it seems I was reading notifications top-down on GitHub and didn't notice that meant the issue was closed after the release. Ooops. I'll stand by for the next release. Please make it soon ;-)
