### ISSUE TITLE
ERROR Could not the reach OpenID Connect provider.

### ISSUE THREAD

**Issue by seseso** [nextcloud/user_oidc#355]
I have configured my provider:
`+----+------------+------------+---------------------------------------------------------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------+
| ID | Identifier | Client ID  | Discovery endpoint                                                  | Advanced settings    |                                                                                                                                    |
+----+------------+------------+---------------------------------------------------------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------+
| 2  | DCER       | dcer-cloud | https://[MY OIDC server URL]/auth/realms/[MY REALM]/protocol/openid-connect/auth | openid email profile | {"mappingDisplayName":"name","mappingEmail":"email","mappingQuota":"quota","mappingUid":"sub","uniqueUid":"0","checkBearer":false} |
+----+------------+------------+---------------------------------------------------------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------+
`
(Both [MY OIDC server URL] and [MY REALM] are correct and I'm can authenticate with it)
but when I click on the button provider for login, I get the error: **Could not the reach OpenID Connect provider.**
On the browser I can see a 404 code for request /apps/user_oidc/login/2

Am I missing something here?

**Comment by NislAr98** [comment]
I am facing the exact same problem.

**Comment by seseso** [comment]
I figured it out. My problem was using plain text (http) instead of Https on my keycloak instance. As soon as I switched to Https, it worked as expected.

**Comment by NislAr98** [comment]
@seseso Could you give me a hint? I am already running keycloak behind traefik with https using Let's Encrypt.

Nextcloud says "Could not the reach OpenID Connect provider."

Keycloak says "type=LOGIN_ERROR, realmId=master, clientId=null, userId=null, ipAddress=172.18.0.1, error=invalid_request"

Thank you!

**Comment by zohaib09** [comment]
> @seseso Could you give me a hint? I am already running keycloak behind traefik with https using Let's Encrypt.
> 
> Nextcloud says "Could not the reach OpenID Connect provider."
> 
> Keycloak says "type=LOGIN_ERROR, realmId=master, clientId=null, userId=null, ipAddress=172.18.0.1, error=invalid_request"
> 
> Thank you!

I have same issue any solution? Keycload 19, NC 24, App OpenID Connect Backend

**Comment by sress** [comment]
> > @seseso Could you give me a hint? I am already running keycloak behind traefik with https using Let's Encrypt.
> > Nextcloud says "Could not the reach OpenID Connect provider."
> > Keycloak says "type=LOGIN_ERROR, realmId=master, clientId=null, userId=null, ipAddress=172.18.0.1, error=invalid_request"
> > Thank you!
> 
> I have same issue any solution? Keycload 19, NC 24, App OpenID Connect Backend

I second that.
Same issue here. Also with Keycloak 19.0.1 and NC 24

**Comment by jkuester** [comment]
> https://[MY OIDC server URL]/auth/realms/[MY REALM]/protocol/openid-connect/auth

For anyone facing this exact error (with the `auth/realms/[MY REALM]/protocol/openid-connect/auth` endpoint), see the more recent discussion here: https://github.com/nextcloud/user_oidc/issues/555
