### ISSUE TITLE
Token <--> Property mapping

### ISSUE THREAD

**Issue by gargamel-cddr** [nextcloud/user_oidc#42]
I used the community openid connect application, which allowed me to define which token property gets mapped to the nextcloud username, quotaSettings, etc.

With this solution, I cannot do that anymore. This results in 
a) my users not being able to find their files and 
b) creation of new users that
c) cannot be found on the user page

I expect to make this mapping configurable, or at least honor the (preferred_)username property of a token. Right now, it seems to just use the *sub* of the token. And to be honest, this official user backend should at least provide the same functionality like the community plugin does.

**Comment by rullzer** [comment]
Migration is not supported from one to the other.
You can still just use the community one if that works better for you.

**Comment by gargamel-cddr** [comment]
Well, as a matter of fact, I cannot do so, because this Plugin doesn‘t uninstall properly, but that‘s another issue I need to open.
But Migration is not my main point here: sub + issuer should be used for uniqueness of the account, but not the username. 

In my opinion, preferred_username from the openid Profile should be used for this. Also, this Plugin does not Support Quota Settings and the Users cannot be found in the User Store. All this is being done by the Community Plugin, therefore I mentioned it so you can get „inspired“ by their implementation. It provides nice Features, and I would‘ve sticked to it if it wasn‘t broken in latest times.

**Comment by juliushaertl** [comment]
That should be possible now in case the OIDC token contains a field for the old user id in use with disabling the unique uid option and setting a custom mapping for the uid with #268
