### ISSUE TITLE
Implement backchannel logout

### ISSUE THREAD

**Issue by eneiluj** [nextcloud/user_oidc#447]
We could support backchannel logout like described in https://openid.net/specs/openid-connect-backchannel-1_0.html

The logic, as I understand it is:
* there's a way to check if it's supported by the provider (attributes of the discovery)
* on login, give the provider our session ID and a backchannel logout URL
* on logout, we call the single logout endpoint (already implemented) and the provider will call the backchannel URL with the session ID as param
* we should close the corresponding session

**Comment by Lycsona** [comment]
I think this is related issue https://github.com/nextcloud/user_oidc/issues/449
