### ISSUE TITLE
Can not logout via Keycloak - Missing parameters id_token_hint

### ISSUE THREAD

**Issue by Lycsona** [nextcloud/user_oidc#449]
I have an issue with logout via Keycloak.

When a user clicks on the logout button, their see:

`Missing parameters: id_token_hint`

The Keycloak logout URL is used properly, but **id_token_hint** which is required is not set. 
This token is issued after the user signs in as an **id_token** value from Keycloak response of auth endpoint. 

Could it be fixed, please? Or could you help to clarify it? Because I am not able to use logout.

**Comment by Igortorrente** [comment]
Same issue

**Comment by DaphneMuller** [comment]
@julien-nc can you look into an effort estimate for this one? It's the top-voted issue among all our team's apps
