### ISSUE TITLE
Cannot create app passwords due to password prompt

### ISSUE THREAD

**Issue by EvanDurfee** [nextcloud/user_oidc#468]
When logged in via a cusom oidc provider (keycloak in my case), I'm prompted for my account password if I try to create an app password. Since I'm not logging in via nextcloud, it's not possible to satisfy this password check.

This seems to be the same issue experienced by the dev of the nextcloud social login plugin: https://github.com/nextcloud/server/issues/9474

Setup:
Fresh install of nextcloud (version 24.0.0),
LDAP user backend plugin enabled and handling user provisioning
OIDC user backend plugin enabled and connected to keycloak. OIDC plugin user id mapped to the ID in ldap, and configured with:
```
  'user_oidc' => [
    'single_logout' => true,
    'auto_provision' => false,
  ],
```

**Comment by benedikt-bartscher** [comment]
I have the same issue with latest nextcloud, user_oidc and authentik (via saml).

**Comment by herrfeuer** [comment]
+1

**Comment by juliushaertl** [comment]
Reference from SAML https://github.com/nextcloud/server/pull/7487/files
