### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Igortorrente** [nextcloud/user_oidc#483]
It would be nice to have a new version now that https://github.com/nextcloud/user_oidc/pull/464 is already merged.

Thanks for the great work!

**Comment by schewara** [comment]
@juliushaertl , @rullzer (adding you directly, as you are listed as the Publisher/Maintainers on (https://apps.nextcloud.com/apps/user_oidc)
It seems, there are newer version available on the Nextcloud Appstore (1.2.0,1.2.1) but no sign of it here, which makes it hard to validate what was changed and what might be fixed/broken in the newer version before updating.

For all users, it would be great to get some update and clarification about the state and the future of this project/repo, as currently it makes a rather abandoned impression.

**Comment by juliushaertl** [comment]
The mentioned PR has been released as version v1.2.1

The releases are hosted in a separate organisation, but I've discussed with @julien-nc recently to probably mirror the releases over to this one as well:

https://github.com/nextcloud-releases/user_oidc/releases/tag/v1.2.1
