### ISSUE TITLE
Provider Identifier can not be changed

### ISSUE THREAD

**Issue by schewara** [nextcloud/user_oidc#487]
When trying to rename the Providers Identifier, the following Error occurs

> Could not update the provider: Provider with the given identifier does not exist

As long as the Identifier Field is writable when updating an existing Provider,
maybe any of the following options could be a viable adjustments:

- be able to rename it
- be disabled for editing
- have an extra settings field to control the display name on the login button
  like it is done in [oauth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#openid-connect-provider)

In addition to that, it would also be helpful if there is any information in the documentation about character limitations of the identifier, as it has a direct effect on the Backchannel logout URL and maybe also other places.

**Comment by Ornanovitch** [comment]
This could be very useful indeed.

**Comment by nc-fkl** [comment]
> This could be very useful indeed.
Hi @schewara and @Ornanovitch,

thank you for your suggestion! The identifier is limited to 128 characters and wont allow more characters in the input field from now on. We've disabled the posibility to edit the identifier once its set and also enabled the character limitation in this PR: https://github.com/nextcloud/user_oidc/pull/714

Therefore i close this issue now, thanks for your contribution!
