### ISSUE TITLE
Could not reach the OpenID Connect provider.

### ISSUE THREAD

**Issue by jefke24** [nextcloud/user_oidc#534]
Is it possible that the user_oidc app can not handle self signed certificates?

I am getting the error "Could not reach the OpenID Connect provider." when trying to use keycloak integrated with nextcloud on the login page.

When looking at the logs:
{"reqId":"cHs8D4yoTqzbga58iBbx","level":4,"time":"2022-11-12T21:16:36+00:00","remoteAddr":"<redacted>","user":"--","app":"user_oidc","method":"GET","url":"/apps/user_oidc/login/2","message":"Could not reach the provider at URL https://redacted/.well-known/openid-configuration","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0","version":"25.0.1.1","data":{"app":"user_oidc"}}

So the app claims not being able to connect to that URL.

Funny thing is:

root@8678d04dba4f:/var/www/html/data# curl https://redacted/.well-known/openid-configuration
curl: (60) SSL: unable to obtain common name from peer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Then, let's try this:

curl -k https://redacted/.well-known/openid-configuration
{"issuer":"redacted","authorization_endpoint":"https://redacted/protocol/openid-connect/auth","token_endpoint":"https://redacted/protocol/openid-connect/token","introspection_endpoint":"https://redacted/protocol/openid-connect/token/introspect", .........

I'm running this internally in my home network behind a reverse proxy.

Any idea how I can solve this?

1) would it indeed be linked to the selfsigned certificate?
2) is this expected behaviour or is a workaround possible?

**Comment by jerrac** [comment]
@jefke24 I'm running into this exact issue. Did you find a work around?
