### ISSUE TITLE
Nextcloud claims "Could not reach the OpenID Connect provider.", keycloak logs says ClientID=null

### ISSUE THREAD

**Issue by eyduh** [nextcloud/user_oidc#555]
I'm trying to setup keycloak as the user backend and connect it using this plugin. 

My server is running proxmox 7, I have one production docker box on there where I have nextcloud and collabora installed through docker-compose. I also have some LXC containers running DBs, file server and keycloak/ldap.

Nextcloud is installed using the linuxserver.io (alpine based) container, connecting to a postgres db running in an lxc container. It installs fine and only complains about not having email set up yet in the security overview. Let's say it's on https://nextcloud.a.domain

Keycloak is installed into an open ldap lxc container and is set up to use the ldap server for user federation, and later for some applications that don't support oidc. Let's say it's on https://keycloak.a.domain

Both applications are running behind a SSL/TLS terminating nginx reverse proxy and are reachable on their respective subdomains, using a wildcard ssl cert for (a.domain, *.a.domain). On the local network nextcloud comes with a self-signed cert and Keycloak is configured to use the same wildcard cert as on the public front end.

So, [following the guide at first](https://www.schiessle.org/articles/2020/07/26/nextcloud-and-openid-connect/) and [later using the ReadMe.md info](https://github.com/nextcloud/user_oidc#readme), I set up a Client in keycloak and add the right info into the addon:

```
docker exec -it nextcloud occ user_oidc:provider anamefortheIDP --clientid="nextcloud"     --clientsecret="theclientsecretfromtheclientinkeycloak" --discoveryuri="https://keycloak.a.domain/realms/my-realm/protocol/openid-connect/auth"

```

Both the webinterface as well as using 'occ' cli with the same result, in both cases I get the same error message on the front end / login page of Nextcloud:
![image](https://user-images.githubusercontent.com/29815625/211087404-f08e7885-f6d1-477e-8e3a-efd6adc1a755.png)
"Could not reach the OpenID Connect provider."

If I follow the logs in nextcloud using `docker exec -it nextcloud occ log:watch`, I see:
```
  Error    user_oidc          No Bearer token                                                                                                                    2023-01-06T19:58:03+00:00 

  Fatal    user_oidc          Could not reach the provider at URL https://keycloak.a.domain/realms/my-realm/protocol/openid-connect/auth                      2023-01-06T19:58:09+00:00 

```

Nextcloud can however reach said server just fine:
```
docker exec -it nextcloud curl https://keycloak.a.domain/realms/my-realm/protocol/openid-connect/auth
<!DOCTYPE html>
<html class="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="robots" content="noindex, nofollow">

    <title>Sign in to my-realm</title>
    <link rel="icon" href="/resources/oysvj/login/base/img/favicon.ico" />
</head>

<body class="">
<div class="">
    <div id="kc-header" class="">
        <div id="kc-header-wrapper"
             class="">my-realm</div>
    </div>
    <div class="">
        <header class="">
                <h1 id="kc-page-title">        We are sorry...
</h1>
      </header>
      <div id="kc-content">
        <div id="kc-content-wrapper">


        <div id="kc-error-message">
            <p class="instruction">Invalid Request</p>
        </div>



        </div>
      </div>

    </div>
  </div>
</body>
</html>

```
(other than that the request here obviously is invalid.)

Ok, let's check the other end. I go to https://nextcloud.a.domain and hit the Log in with my-realm button
```
tail -f /var/log/syslog
Jan  6 21:05:00 keycloakhost kc.sh[236]: 2023-01-06 21:05:00,930 WARN  [org.keycloak.protocol.oidc.endpoints.request.AuthorizationEndpointRequestParserProcessor] (executor-thread-7) Parameter 'client_id' not present or present multiple times in the HTTP request parameters
Jan  6 21:05:00 keycloakhost kc.sh[236]: 2023-01-06 21:05:00,931 WARN  [org.keycloak.events] (executor-thread-7) type=LOGIN_ERROR, realmId=8anormala-look-ingu-uuid-12345678, clientId=null, userId=null, ipAddress=my-public-ip-address, error=invalid_request
```

Seems the addon either fails to parse the ClientID from occ/webgui or it fails to pass on the ClientID to keycloak somewhere along the line.

**Comment by Igortorrente** [comment]
Different setup, same issue.

**Comment by Igortorrente** [comment]
Hi @eyduh ,

I managed to solve the issue by adding `'allow_local_remote_servers' => true` to `config.php `.

I my case I was also receiving this log below:

```
[no app in context] Warning: Host 192.XXX.XXX.XXX was not connected to because it violates local access rules

GET /apps/user_oidc/login/1
from 177.144.148.115 at 2023-01-12T00:49:20+00:00
```

Maybe worth trying!

**Comment by eyduh** [comment]
> I managed to solve the issue by adding `'allow_local_remote_servers' => true` to `config.php `.

Tried this but same result :(

**Comment by jkuester** [comment]
> discoveryuri="https://keycloak.a.domain/realms/my-realm/protocol/openid-connect/auth"

I experienced the exact same behavior described in this issue. After a bunch of debugging I realized that the value recommended by the jumpstart blog post for the "Discovery Endpoint " is actually incorrect.  As I noted in [this issue](https://github.com/nextcloud/user_oidc/issues/583), the Discovery Endpoint should actually just be set to the "OpenID Endpoint Configuration URL", itself, and NOT the extracted `authorization_endpoint` value.  So, for KeyCloak it should be something like `https://keycloak.a.domain/auth/realms/my-realm/.well-known/openid-configuration`.

**Comment by murphysprings** [comment]
@jkuester Thank you for pointing that out. That was part of it.

Another item I found was that Keycloak was expecting the request to be SSL, but since I have Keycloak behind a reverse proxy that is handling the SSL piece of it, the request is plain HTTP.

To resolve that, go to Realm Settings --> Login and then change "Require SSL" to "none" (the default is external requests).

![image](https://user-images.githubusercontent.com/31575210/222936473-86cf2ccb-6e36-4d2b-b72f-08fcad4febe3.png)

**Comment by Torxed** [comment]
Probably a small margin of people that will have the issue I'm having, but the same error message applies to invalid TLS certificates. Meaning if you're running self-hosted with self-signed CA structure this happens as well.

```
$ docker exec -it nextcloud curl https://keycloak.a.domain/realms/my-realm/protocol/openid-connect/auth
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by eyduh** [comment]
This could be it, I'm running nextcloud with self signed certs behind a SSL/TLS terminating proxy which handles all the certs outwards.

The keycloak instance is also set up like this tho and uses the same wildcard cert outwards so if they try and talk to eachother through their fqdn they should only see the real wildcard cert, not the self signed ones they use internally.

**Comment by eyduh** [comment]
> > discoveryuri="https://keycloak.a.domain/realms/my-realm/protocol/openid-connect/auth"
> 
> I experienced the exact same behavior described in this issue. After a bunch of debugging I realized that the value recommended by the jumpstart blog post for the "Discovery Endpoint " is actually incorrect. As I noted in [this issue](https://github.com/nextcloud/user_oidc/issues/583), the Discovery Endpoint should actually just be set to the "OpenID Endpoint Configuration URL", itself, and NOT the extracted `authorization_endpoint` value. So, for KeyCloak it should be something like `https://keycloak.a.domain/auth/realms/my-realm/.well-known/openid-configuration`.

I havent looked at this for a bit but will try this solution soon

**Comment by eyduh** [comment]
> > > discoveryuri="https://keycloak.a.domain/realms/my-realm/protocol/openid-connect/auth"
> > 
> > 
> > I experienced the exact same behavior described in this issue. After a bunch of debugging I realized that the value recommended by the jumpstart blog post for the "Discovery Endpoint " is actually incorrect. As I noted in [this issue](https://github.com/nextcloud/user_oidc/issues/583), the Discovery Endpoint should actually just be set to the "OpenID Endpoint Configuration URL", itself, and NOT the extracted `authorization_endpoint` value. So, for KeyCloak it should be something like `https://keycloak.a.domain/auth/realms/my-realm/.well-known/openid-configuration`.
> 
> I havent looked at this for a bit but will try this solution soon



> So, for KeyCloak it should be something like `https://keycloak.a.domain/auth/realms/my-realm/.well-known/openid-configuration`.

This was the issue.

It was also mentioned in this blog post https://www.schiessle.org/articles/2023/07/04/nextcloud-and-openid-connect/
so might try and make a pull request for the link in the readme to be updated to this new version.

Cheers! <3

(Another thing to be aware of is if you have tried different oidc solutions to make sure that only one is active in the nextcloud instance as they might override eachother on the login page. I had this with social_login despite disabling it using `occ` and had to reenable it and delete the provider in that app then disable it before the login button was the correct one)

**Comment by eyduh** [comment]
> > > discoveryuri="https://keycloak.a.domain/realms/my-realm/protocol/openid-connect/auth"
> > 
> > 
> > I experienced the exact same behavior described in this issue. After a bunch of debugging I realized that the value recommended by the jumpstart blog post for the "Discovery Endpoint " is actually incorrect. As I noted in [this issue](https://github.com/nextcloud/user_oidc/issues/583), the Discovery Endpoint should actually just be set to the "OpenID Endpoint Configuration URL", itself, and NOT the extracted `authorization_endpoint` value. So, for KeyCloak it should be something like `https://keycloak.a.domain/auth/realms/my-realm/.well-known/openid-configuration`.
> 
> I havent looked at this for a bit but will try this solution soon



> So, for KeyCloak it should be something like `https://keycloak.a.domain/auth/realms/my-realm/.well-known/openid-configuration`.

This was the issue.

It was also mentioned in this blog post https://www.schiessle.org/articles/2023/07/04/nextcloud-and-openid-connect/
so might try and make a pull request for the link in the readme to be updated to this new version.

Cheers! <3

(Another thing to be aware of is if you have tried different oidc solutions to make sure that only one is active in the nextcloud instance as they might override eachother on the login page. I had this with social_login despite disabling it using `occ` and had to reenable it and delete the provider in that app then disable it before the login button was the correct one)

**Comment by eyduh** [comment]
Updated the readme in this pull request:
https://github.com/nextcloud/user_oidc/pull/655

**Comment by AndreasBBS** [comment]
> @jkuester Thank you for pointing that out. That was part of it.
> 
> Another item I found was that Keycloak was expecting the request to be SSL, but since I have Keycloak behind a reverse proxy that is handling the SSL piece of it, the request is plain HTTP.
> 
> To resolve that, go to Realm Settings --> Login and then change "Require SSL" to "none" (the default is external requests).
> 
> ![image](https://user-images.githubusercontent.com/31575210/222936473-86cf2ccb-6e36-4d2b-b72f-08fcad4febe3.png)

This is not a solution because it leaves the whole Realm unprotected... Nextcloud needs to be able to make https request regardless of being behind a reverse proxy running in http mode.

**Comment by AndreasBBS** [comment]
For anyone struggling with having this running with Keycloak with TLS/SSL I just used this plugin instead and it works great https://apps.nextcloud.com/apps/sociallogin

**Comment by bialask-daiteap** [comment]
I had the same issue and it proved to be caused by the fact that Nextcloud was running as docker container and hence keycloak server installed locally was not visible when referring to it as 'localhost'. The solution was to refer to the provider URL as 'host.docker.internal' under which locallhost is visible inside the docker container:
http://host.docker.internal:8180/realms/OICDDemo/.well-known/openid-configuration

Additionally, for the domein 'host.docker.internal' to lead to the keycloak outside of docker (during real login) , I added mapping of 127.0.0.1 to host.docker.internal in /etc/hosts

**Comment by LeonStoldt** [comment]
Just wanted to throw in another possibility: If you're using Cloudflare and have set up firewall rules (like [blocking bots based on user agent](https://medium.com/@liewcf/how-to-use-cloudflare-firewall-rules-to-protect-your-web-application-fc3e5167b4bc)), and you encounter this issue where `curl https://auth.example.com/.well-known/openid-configuration` works fine but Nextcloud doesn't, make sure to check your Cloudflare Firewall events. You might find Nextcloud being blocked. ([Cloudflare Dashboard](https://dash.cloudflare.com/) -> Choose your domain -> Security -> Events)

This detail cost me some time. It was suspicious that Nginx Reverse Proxy logged events when I called the endpoint via curl but not when Nextcloud made the call. Nextcloud's GuzzleHttp Provider uses the following user agent: `Nextcloud Server Crawler`.

Oh, and a heads-up for those following tutorials like [Nextcloud-OIDC-with-Authentik](https://blog.cubieserver.de/2022/complete-guide-to-nextcloud-oidc-authentication-with-authentik/): CLI setups don't seem to verify if they can reach the discovery URL. I only stumbled upon this when I tried tweaking some settings through the UI later on.

And for those hunting down the often-mentioned schiessle.org blog post for setting up with Keycloak, it's currently not accessible, but it's archived on the [Internet Archive](https://web.archive.org/web/20230804063647/https://www.schiessle.org/articles/2023/07/04/nextcloud-and-openid-connect/).

Hope this info saves someone else some time!

**Comment by EvivrusR** [comment]
I know this is an old thread but I had the same issue and for me my issue boiled down to the Self Signed Cert. It was causing NextCloud to fail to communicate with my Authentik server. 
I resolved the issue by implementing a Lets Encrypt certificate on the Authentik server allowing NextCloud to make the connection. (A test you can do is see if you can make the connection work insecurely with only http. If it works might it could be a certificate issue.)
