### ISSUE TITLE
Map Roles from KeyCloak to Nextcloud

### ISSUE THREAD

**Issue by geilmaker** [nextcloud/user_oidc#570]
Hello :)

I tried the social login plugin, but could not find the logout mechanism that you support in this plugin, thats awesome!
But now I miss another part - is it somehow possible to use the mapped roles from keycloak inside nextcloud? Is there any possibility to read the roles inside nextcloud and attach them to the user like social login plugin is doing? Or is this feature simply not supported (yet)?

Thanks for your time and effort!

Have a good one :)

**Comment by isdnfan** [comment]
There is a setting called "group mapping" on identity provider config:

![image](https://user-images.githubusercontent.com/18125597/236672603-b81810f3-25b7-40d6-9858-b7c0407579a7.png)

you can configure roles in you Keycloak by adding them directly of mapping them to a Keycloak group within your Keycloak "client" config:

![image](https://user-images.githubusercontent.com/18125597/236672813-a15a9e33-ea66-48c3-888d-5aecabdff97a.png)

Keycloak "role" becomes a group membership in Nextcloud.

**Comment by geilmaker** [comment]
Thank you very much!

I was just starting with keycloak and nextcloud oidc logins... I think I tried that, but filled the role names in and not the claim name, guess that was my problem... Now its working :)

**Comment by markus2330** [comment]
Thank you for this description here, I tried to do the same. Unfortunately, for me the groups mapping is greyed out:

![Image](https://github.com/user-attachments/assets/44c381e6-cd3d-4b8d-a2cb-ccd35c21c651)

How can I fix this?

**Comment by da-wilky** [comment]
Sorry, I can't help you on this anymore.
Now I am using https://github.com/pulsejet/nextcloud-oidc-login for my nextcloud instances, in case you want to have a look into this.

**Comment by markus2330** [comment]
I think I found it, "Use group provisioning." needs to be checked.
