### ISSUE TITLE
Jumpstart docs blog post is out-of-date/incorrect

### ISSUE THREAD

**Issue by jkuester** [nextcloud/user_oidc#583]
The very top of the README for this project links to [this helpful blog post](https://www.schiessle.org/articles/2020/07/26/nextcloud-and-openid-connect/) as a "proper jumpstart" guide.  Unfortunately, as I was recently trying to follow the steps from the blog post I found a couple issues that have me (a beginner to OIDC) a lot of trouble and confusion.

1. The blog post seems to imply that the "Discovery Endpoint" value in NextCloud should just be set to the `authorization_endpoint` value for the KeyCloak realm.  Using this value results in a `Could not reach the OpenID Connect provider.` similar to what is described in https://github.com/nextcloud/user_oidc/issues/555.  Instead, the Discovery Endpoint value should just be set to the KeyCloak Realm's "OpenID Endpoint Configuration" URL. (e.g. `https://keycloak.example.com/auth/realms/examplerealm/.well-known/openid-configuration` )

2. The blog post recommends updating the default KeyCloak client Valid Redirect URI to be `...index.php/apps/user_oidc/code` ("the one proposed by the Nextcloud OIDC app").  That allows for successful redirection in the _login workflow_, but I experienced errors in the _logout workflow_ because it was trying to redirect back to a different endpoint.  Just using the default wildcard Valid Redirect URI worked fine for me.

I think it would be helpful to have a more up-to-date quickstart guild (or at least include some corrections/disclaimers when linking to the existing one)...  Thanks!

**Comment by NlightN22** [comment]
Thanks! You help me to solve same problem!

**Comment by jkuester** [comment]
Closing this since the README now links to the [updated blog post](https://www.schiessle.org/articles/2023/07/04/nextcloud-and-openid-connect/)!
