### ISSUE TITLE
Feature: Add option to set logout URL manually

### ISSUE THREAD

**Issue by rhclayto** [nextcloud/user_oidc#599]
Would it be possible to add a configuration option, either in the UI or in the config file, to manually set the logout URL? The OpenID provider I am using, Authelia, doesn't seem to provide a `end_session_endpoint` value in its `/.well-known/openid-configuration` response.

Later edit: But they do have a logout page, which if redirected to, serves the purpose. If we could redirect to that page, it would allow us to log out of SSO from within Nextcloud.

**Comment by dillfrescott** [comment]
I would love this!!!

**Comment by dillfrescott** [comment]
@rhclayto a temporary way around this until they add it officially is to copy the openid-config, edit the `end_session_endpoint` manually, paste the edited config as a github gist, and then change the config url in the app to the raw gist link.
