### ISSUE TITLE
groups mapping only works if scope is named groups. Mapping doesn't work.

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/user_oidc#648]
The good news: groups mapping seem to work ( #502) . 
Bad news: this only works if the groups are delivered in the scope groups.
If I deliver them in roles and try to map roles->groups, I see errors like 
`foreach() argument must be of type array|object, null given at /data/apps/user_oidc/lib/Service/ProvisioningService.php#146`

**Comment by isdnfan** [comment]
for me mapping from custom claim works with Keycloak and Authentik. Please double check your "roles" claim is part of the scopes you request from IdP. (I had hard time to find my custom mapping was adding the claim to custom scope)
