### ISSUE TITLE
Improve documentation of group provisioning

### ISSUE THREAD

**Issue by Ra72xx** [nextcloud/user_oidc#653]
I like to get groups in Nextcloud from my Authentik instance and - being not a specialist in authentification methods - the provided information does not really help me.

First step: User management worked quite easy following this guide: https://blog.cubieserver.de/2022/complete-guide-to-nextcloud-oidc-authentication-with-authentik/
Second step: For groups there is no coherent documentation to be found, not even with the --help command line option.  I had to rely on the hints found in [PR]https://github.com/nextcloud/user_oidc/pull/502(url), especially
```
occ config:app:set user_oidc provider-1-groupProvisioning --value=1
occ user_oidc:provider "Authentik" --scope="openid email profile groups"
```
However, I seem to have a misconfiguration of Authentik as no groups are provided. On the contrary, users provided by Authentik get thrown out of local Nextcloud groups (i.e. the "admin" group).

As there is no real doc yet for the group provisioning in user_oidc documentation (and, to be sure, Authentik documentation seems quite exhaustive, but is in many cases unusable for non-specialists, too). I don't know how to properly set up group provisioning while keeping at least the local admin group.

**Comment by TheManchineel** [comment]
Funny enough, I've made the exact same journey as you and ended up where you're currently at. Did you ever figure this out?

**Comment by Ra72xx** [comment]
No. I ended up re-creating the necessary Authentik groups locally in Nextcloud (for my small setup). However, this is not really an elegant solution...

**Comment by TheManchineel** [comment]
Figured to do just as much. Obviously this would be a pain in any kind of large/enterprise installation. For my own personal use it "works" I guess...

**Comment by Ra72xx** [comment]
It would be really great if this IMHO very basic setup would get some more end-user documentation. I can't really image that we two are the only ones wanting to use the OIDC provider's group setup in die OIDC-enabled application ;-) .

**Comment by isdnfan** [comment]
Nextcloud group provisioning works very straight forward - based on the OIDC claim it adds/removes the user from the groups (and auto-creates NC groups if needed).

Mapping the group can be done easily, hardest part is on Authentik side. here my setup using custom claim "roles"

in Authentik create custom property mapping (my code is little more complex as I want the groups in Authentik to have application related prefix "dev-nc_" in this case but don't want to see this prefix in NC so I remove the in the mapping)

![image](https://github.com/nextcloud/user_oidc/assets/18125597/5bb36077-ec20-4b2d-9364-692a7a6e077e)

in provider > advanced settings add the custom mapping

![image](https://github.com/nextcloud/user_oidc/assets/18125597/dce56eb9-166d-499d-9eb3-9076ac40f531)

in application > preview verify the "roles" claim was added:

![image](https://github.com/nextcloud/user_oidc/assets/18125597/1e59429d-9ae5-4fc6-9936-8f3955f83a6d)

in NC user_oidc settings map the claim and enable group provisioning

![image](https://github.com/nextcloud/user_oidc/assets/18125597/f3b98966-af79-4691-8fdc-7e97f8864752)


review the process with more details here: https://24xsiempre.com/en/kasten-k10-authentik/

**Comment by TheManchineel** [comment]
@isdnfan thanks! This worked wonderfully

In my case, this is what I did:

```py
nc_groups = [
    (i if i != "Nextcloud Admin" else "admin") for i in request.user.ak_groups.all().map("name")
]

return {"nc_groups": nc_groups}
```

then enabled the mapping for the Nextcloud provider, and on the NC side I enabled group provisioning and added the `nc_groups` mapping as the source attribute.

One question: is there any way to have groups "sync" earlier than the next token expiration/sign in?

**Comment by Ra72xx** [comment]
BTW, has anybody a mapping to use Authentik avatars in Nextcloud?

**Comment by Ra72xx** [comment]
Unfortunately, I don't get any of the versions above to work. As soon as I enable group provisioning, the user gets thrown out of any group on the next login. E.g. for the example of @TheManchineel 

**Nextcloud user_openidc:**
![Eingefügtes Bild](https://github.com/nextcloud/user_oidc/assets/3582007/1f1f8867-3ba4-4450-83da-982b0a0b69fe)

**Authentik:**
![Eingefügtes Bild 1](https://github.com/nextcloud/user_oidc/assets/3582007/a0202d51-0d09-4547-8d11-c11319b89d29)
![Eingefügtes Bild 2](https://github.com/nextcloud/user_oidc/assets/3582007/c8e3cd59-349c-4637-9c80-417e6b0d6df0)

Am I misunderstanding something? If I try the property mapping with the test icon in the property mapping section, it seems to work as expected. I don't have "Application>Preview" button?!

**Comment by wrenix** [comment]
How to set this programmatically? there is no `--mapping-groups=` in the `occ user_oidc:provider` command

**Comment by ManfredWisniewski** [comment]
@Ra72xx did you ever resolve this? I am having the same problem. Everytime my users log in they are thrown out of the groups that I assigned them.

**Comment by Ra72xx** [comment]
No, I did not further attempts to solve this issue.

**Comment by danthonywalker** [comment]
Has anyone been able to get this working?

**Comment by Ra72xx** [comment]
It works for me with Authentik. I don't know exactly how I did it, but I somehow simply adapted the official docs to my needs, wasn't that difficult in the end (https://docs.goauthentik.io/integrations/services/nextcloud/).

**Comment by Ra72xx** [comment]
So I should probably close this issue ;-) .

**Comment by ManfredWisniewski** [comment]
Yes it works for me now too. My problem was a simple misunderstanding: users and their info are synced from Authentik to nextcloud - not the other way around. I created and assigned the groups in Authentik and once they log in they have the groups they were assigned in Authentik.
