### ISSUE TITLE
additional attributes

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/user_oidc#661]
Do you plan to add the possibility to receive additional attributes like address, phone (just like nextcloudQuota is already available)?

**Comment by nc-fkl** [comment]
Hi @joergmschulz , thats a good point! We are working on it currently in https://github.com/nextcloud/user_oidc/tree/fix/661/additional-attributes

**Comment by nc-fkl** [comment]
Hi @joergmschulz , this pr is now merged into the main branch. Thanks again for the contribution of this idea!
