### ISSUE TITLE
Disable standard login & auto-redirect to provider on load

### ISSUE THREAD

**Issue by Zegorax** [nextcloud/user_oidc#669]
Hello everyone,

Is it possible to disable basic login and redirect to the OIDC provider automatically when loading the Nextcloud homepage ?

**Comment by isdnfan** [comment]
is well documented:

# [Disable other login methods](https://github.com/nextcloud/user_oidc#disable-other-login-methods)

If there is only one OpenID Connect provider configured, it can be made the default login method and the user would get redirected to the provider immediately for the login. Admins can still use the regular login through adding the ?direct=1 parameter to the login URL.

`sudo -u www-data php var/www/nextcloud/occ config:app:set --value=0 user_oidc allow_multiple_user_backends`

**Comment by Zegorax** [comment]
Thanks a lot! I missed it unfortunately.
