### ISSUE TITLE
Code Verifier And Code Challenge

### ISSUE THREAD

**Issue by noldoreldar** [nextcloud/user_oidc#710]
Our OpenId Identity Provider (which is IdentiyServer4) only accepts "Code Verifier" method with S256.

Login Redirect Template is like this: 

`https://idsrvr.example.com/account/login?returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dclientapp-openId%26redirect_uri%3Dhttps%253A%252F%252Fclientapp.example.com%252Flogin%26response_type%3Dcode%26code_challenge%3DvdP***************4fg%26code_challenge_method%3DS256%26scope%3Dopenid%2520profile%2520email%2520clientapp.login%26state%3D9h*******zc3A
`
Is there any way I can modify the configuration to use Code Challenge method instead of "state" and "nonce" ??

EDIT: Seems like what I described is called "PKCE Flow". 
-- **So this is the duplicate of same issue already mentioned here: https://github.com/nextcloud/user_oidc/issues/344**

**Comment by nc-fkl** [comment]
Fixed and closed by merge of #697
