### ISSUE TITLE
Error after updating to 1.3.5

### ISSUE THREAD

**Issue by dvoijen** [nextcloud/user_oidc#735]
Steps to reproduce

update from 1.3.3 to 1.3.5

Expected behavior

OPENID Login page shown
Actual behaviour

When visiting the page i get this error:

```
{
    "error": "invalid_request",
    "error_description": "Invalid request"
}
```
Downgrade to 1.3.3 was a workaround but after the update to 28.0.0.0 we cannot downgrade this app anymore.

There is no log in Nextcloud.

**Comment by julien-nc** [comment]
Can you provide the full URL that is accessed? You can remove the domain name, we need to see if there is a missing or malformed parameter.

Also, what is your OpenID provider? Keycloak? Something else?

**Comment by dvoijen** [comment]
Julien,

Ok, browse to: https://nc.sisnl.net
You will see this error: {"error":"invalid_request","error_description":"Invalid request"}
When (F12 Google) i see in the network: 403 Forbidden

The Login Redirect URL i use is: https://nc.sisnl.net/apps/user_oidc/code

**Comment by dvoijen** [comment]
And for openID Provider i use Entrust

**Comment by dvoijen** [comment]
@julien-nc Is there anything we can do about this?

**Comment by dvoijen** [comment]
I created a workaround for now.
unpacked the old version an edited the info.xml in the appinfo folder to version 1.3.5

**Comment by julien-nc** [comment]
The only thing that could have broken the login flow is the addition of PKCE. I thought it would be ignored by providers which don't support it. If my guess is right, your provider is refusing the extra PKCE-related parameter we now send.

Can you try to use the real v1.3.5 again and just comment out line 395 of `apps/user_oidc/lib/Controller/LoginController.php` which should look like
``` php
'code_verifier' => $code_verifier, // Set for the PKCE flow
```
So just change it to
``` php
// 'code_verifier' => $code_verifier, // Set for the PKCE flow
```

**Comment by dvoijen** [comment]
Unfortunatly the same result, try and browse to https://nc.sisnl.net now i will leave this 30 min so you can see what it does.

**Comment by julien-nc** [comment]
Ok it's a bit clearer now, could you try commenting the same line as before but also lines 288 and 289 which look like:
``` php
'code_challenge' => $this->toCodeChallenge($code_verifier),
'code_challenge_method' => 'S256',
```

**Comment by dvoijen** [comment]
@julien-nc That fixed it, working now.

**Comment by julien-nc** [comment]
Thanks for the feedback, i'll then implement a switch to toggle PKCE (disabled by default).
