### ISSUE TITLE
Authentik - account informations problem

### ISSUE THREAD

**Issue by NhProGamer** [nextcloud/user_oidc#757]
i followed [that](https://goauthentik.io/integrations/services/nextcloud/) tutorial for setting up OIDC with Authentik but whan i log in with authentik user there are no attributes at all like email, name etc AND the account's name is an UUID

**Comment by BeastleeUK** [comment]
@NhProGamer  did you fix this? I have  a similar issue, it only gets the email but still uses a UUID for the username. I've verified the output in authentik will be what is expected but Nextcloud doesn't pick any of it up.

**Comment by minosimo** [comment]
Did either of you solve the issue? Running into the same thing with VoidAuth, other services do get the email and name.

**Comment by NhProGamer** [comment]
> Did either of you solve the issue? Running into the same thing with VoidAuth, other services do get the email and name.

Hi! There is probably an issue in your claims settings, ask to an AI it will fix your problem quickly, i cannot test or show you something as I switched et Seafile
