### ISSUE TITLE
Fix version!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by DenuxPlays** [nextcloud/user_oidc#802]
Since version 4.0.0 there is a really stupid requirement:
![image](https://github.com/nextcloud/user_oidc/assets/83671398/69f650f7-81cb-4a8e-ab46-00fbe6174280)

**Comment by julien-nc** [comment]
Which version of Nextcloud are you using? The release for Nextcloud 25 and upper is coming in a few minutes.

**Comment by DenuxPlays** [comment]
> Which version of Nextcloud are you using? The release for Nextcloud 25 and upper is coming in a few minutes.

Nextcloud 27
using nextcloud AIO

But the App itself is unusable when I enter the admin settings of it I get greeted with this:
![image](https://github.com/nextcloud/user_oidc/assets/83671398/9043a544-3e79-4329-8160-1b1e1df32f77)

**Comment by DenuxPlays** [comment]
Log:
![image](https://github.com/nextcloud/user_oidc/assets/83671398/71ee4f5c-cabc-45d3-9ca9-22d493d19bc9)

**Comment by julien-nc** [comment]
Did you enable v4.0.0 on NC 27?

**Comment by julien-nc** [comment]
If you forced NC 27 to enable user_oidc v4.0.0, please update to v5.0.1 which is now out.

If you are already using user_oidc v5.0.1, I would need the complete server log lines you mentioned (nextcloud/data/nextcloud.log).

**Comment by DenuxPlays** [comment]
> If you forced NC 27 to enable user_oidc v4.0.0, please update to v5.0.1 which is now out.
> 
> 
> 
> If you are already using user_oidc v5.0.1, I would need the complete server log lines you mentioned (nextcloud/data/nextcloud.log).

I used v4.0.0
I saw that v5.0.1 was out but the appstore in nextcloud still things that v4.0.0 is the latest version.
Haven't found a way to force an update.
I'll try it later again

**Comment by DenuxPlays** [comment]
With v5.0.1 its fixed.
Thank you
