### ISSUE TITLE
Errors in logs regarding undefined array key 'end_session_endpoint'

### ISSUE THREAD

**Issue by sebrhex** [nextcloud/user_oidc#847]
Hi,

using the following configuration
```json
{
    "system": {
[...]
        "allow_user_to_change_display_name": false,
        "lost_password_link": "disabled",
        "user_oidc": {
            "use_pkce": true
        }
    },
    "apps": {
[...]
       "user_oidc": {
            "installed_version": "5.0.2",
            "types": "authentication",
            "enabled": "yes",
            "allow_multiple_user_backends": "1",
            "provider-1-checkBearer": "0",
            "provider-1-sendIdTokenHint": "0",
            "provider-1-uniqueUid": "0",
            "provider-1-mappingUid": "preferred_username",
            "provider-1-groupProvisioning": "1",
            "provider-1-providerBasedId": "0",
            "provider-1-jwksCache": ""
            "provider-1-jwksCacheTimestamp": "1714390135"
        },
[...]
}
```
with each oidc login and logout the log is filling with `Undefined array key "end_session_endpoint" at /var/www/html/custom_apps/user_oidc/lib/Controller/LoginController.php#597`.

Our oidc provider doesn't provide an appropriate URL and the setting is marked as optional, thus showing up with `null` when I look at `occ --output=json user_oidc:provider`.

Is there a workaround or will this require a fix accepting the `null` value?

Thanks - seb

**Comment by julien-nc** [comment]
Thanks for reporting this. Let's fix it in #848
