### ISSUE TITLE
Using Biography mapping causes internal server error

### ISSUE THREAD

**Issue by skyeBreach** [nextcloud/user_oidc#887]
So i havent seen this mentioned in any threads but assigning an attribute mapping to biography crashes when the inputted data is anything other than null or an empty string. I think this is most likely due to a bad condition as the error message is inversed of what i am giving it. Here is the data that is being passed in and the associated errors:
![image](https://github.com/nextcloud/user_oidc/assets/106411161/9e616901-0054-4449-8766-a1ee7233e1ac)
![image](https://github.com/nextcloud/user_oidc/assets/106411161/047328a2-345b-4dd4-a4aa-330ee3485fd1)
![image](https://github.com/nextcloud/user_oidc/assets/106411161/d24b382a-2231-42c3-a578-ecb065c3fb9b)
![image](https://github.com/nextcloud/user_oidc/assets/106411161/52e52dd6-cbb5-442b-9243-2f90a3bc70fd)

**Comment by julien-nc** [comment]
Thanks for reporting this issue. Can you try changing line 302 of `lib/Service/ProvisioningService.php` from
``` php
$event = new AttributeMappedEvent(ProviderService::SETTING_MAPPING_BIOGRAPHY, $idTokenPayload, $biography);
```
to
``` php
$event = new AttributeMappedEvent(ProviderService::SETTING_MAPPING_BIOGRAPHY, $idTokenPayload, $gender);
```

If it fixes it, i'll make a PR soon.

**Comment by julien-nc** [comment]
Thank you for the feedback! Here is the PR: https://github.com/nextcloud/user_oidc/pull/888
I'll make a release once it's merged.
