### ISSUE TITLE
Bug: package.json version and appinfo version differ

### ISSUE THREAD

**Issue by tholewebgods** [nextcloud/user_oidc#895]
The version in the frontend artifact and the version in the app info differ.

https://github.com/nextcloud/user_oidc/blob/v5.0.3/package.json
```
"version": "1.3.2",
```

https://github.com/nextcloud/user_oidc/blob/v5.0.3/appinfo/info.xml
```
<version>5.0.3</version>
```

**Comment by edward-ly** [comment]
I don't believe the version number in `package.json` is being used anywhere, so it doesn't matter what that value is (but I could be wrong). Still closing this as it has already been updated, though.
