### ISSUE TITLE
Column "display_name" uses empty string while being non-nullable

### ISSUE THREAD

**Issue by aszlig** [nextcloud/user_oidc#90]
Since nextcloud/server@50230847ce47133dd0be170457f24bf5e6ac4ab8, the fix via c960f5c1558a2d438a30aa253677d92c596fd837 is no longer sufficient and results in the following error message when enabing the app:

```
Column name "oc_user_oidc"."display_name" is NotNull, but has empty string or null as default.
```

**Comment by gpastuszko** [comment]
Is there currently a workaround for this app to be installed?

**Comment by sachaw** [comment]
So is there a fix for this, as a few people have opened issues, I assume everyone's experiencing this?

**Comment by hurr1k4ne** [comment]
confirm! (NC20.0.4, mariadb:latest  at 13.01.2021)
fresh docker-compose setup, after first run wizard => app_Store install app:

Column name "oc_user_oidc"."display_name" is NotNull, but has empty string or null as default.

**Comment by monkey-b** [comment]
I confirm having the same issue on a docker-compose install (NC 20.0.5 + mariadb:latest)

**Comment by pascal1337** [comment]
can confirm issues. Installing is possible, but when activating

`Column name "oc_user_oidc"."display_name" is NotNull, but has empty string or null as default.`

**Comment by weeman1337** [comment]
Same issue for me NC 20.0.5 Apache Docker image with external MariaDB.

**Comment by zingz0r** [comment]
the issue still exists in version 20.0.6

**Comment by rullzer** [comment]
I'll try to tackle this next when I hopefully have some more time to spare

**Comment by aszlig** [comment]
@rullzer: Thanks a lot, I can confirm that cbad65ff9a4bbb5334414cb3571c666fbcce5a19 addresses the issue.
