### ISSUE TITLE
disable user_oidc, nextcloud is unusable

### ISSUE THREAD

**Issue by mniehren** [nextcloud/user_oidc#912]
Hi,

i've successfully configured user_oidc with an keycloak endpoint and set allow_multiple_user_backends to 0,
so my only login has been over keycloak.

Now i want only to use the "normal" Login, so first i set the flag for allow_multiple_user_backends ti 1 and even,
if i disabled the user_oidc-App, nextcloud does not run anymore, the browser hangs in an endless loop ...

**Comment by joshtrichards** [comment]
There's not enough information here to do anything other than speculate. You'll need to check your browser inspect (network tab) as well as Nextcloud Server log for clues. I suggest posting a query at the Help Forum - https://help.nextcloud.com to troubleshoot from there...
