### ISSUE TITLE
[Bug]: Access forbidden - State token missing in Nextcloud Desktop

### ISSUE THREAD

**Issue by joselameira** [nextcloud/user_oidc#972]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Have OIDC configured (using Keycloak for instance)
2. Make sure you're logged out from Nextcloud on browser 
3. Try to login with Nextcloud Desktop using the OIDC IdP

### Expected behaviour
Login should work correcty

### Actual behaviour
Login fails with the following error

![Image](https://github.com/user-attachments/assets/537acee9-7c39-4b80-a264-b4cb4caca53d)

**Comment by xataxxx** [comment]
Thank you @joselameira and @julien-nc 

I've encountered this same bug after upgrading to the latest nextcloud desktop and nextcloud 30 + all the app updates and couldn't actually pinpoint the reason for the bug, I found a temporary workaround, but this does seem like the right fix for it.

**Comment by xataxxx** [comment]
Fun fact, this patch and the latest 6.1.2 did NOT fix the same error message for my OIDC use case with Talk Desktop. I'll dig a bit further and attempt to get some specific log data of what's going on.

**Comment by joselameira** [comment]
Hi @xataxxx 

That's weird. Just installed Talk Desktop 0.39.0, and Talk Mobile 20.0.2 (on Android) and it's working on both of them.

**Comment by julien-nc** [comment]
Same here. I tested with and without the PR. I'm positive the PR fixed the issue of the missing GET parameters in the redirect URL during the login flow (tested with the desktop client).

**Comment by xataxxx** [comment]
My bad, you are correct, 6.1.2 does fix things. Since I had been debugging I had managed to accidentally overwrite the 6.1.2 LoginController file with the previous version before the update.

**Comment by julien-nc** [comment]
@xataxxx Thanks for the feedback. Closing this then.
