### ISSUE TITLE
[Bug] Internal Server Error

### ISSUE THREAD

**Issue by franco-viotti** [nextcloud/user_oidc#984]
### Steps to reproduce
1. Install the app “OpenID Connect user backend”

### Expected behaviour
I would expect to be able to log in using mi OIDC provider after setting it up, but got that Internal Server Error instead

### Actual behaviour
This shows in my login page
![Image](https://github.com/user-attachments/assets/51f8215c-f6db-4d78-9467-3d9cfe51a8f6)

### Server configuration

**Web server:** I'm using the following docker-comopose:
`version: '3.8'

services:
  nextcloud:
    image: nextcloud:20
    container_name: nextcloud
    restart: always
    ports:
     - 80:80
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - PHP_MEMORY_LIMIT=512M
    volumes:
      - /srv/nextcloud/html:/var/www/html
      - /srv/nextcloud/data:/var/www/html/data
      - /srv/nextcloud/log:/var/log
      - /srv/nextcloud/config/config.php:/var/www/html/config/config.php
    depends_on:
      - db
  db:
    image: mariadb:10.6
    container_name: db-nextcloud
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /srv/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_INNODB_BUFFER_POOL_SIZE=8G
      - MYSQL_INNODB_LOG_FILE_SIZE=64M
`

**Database:** MySQL

**Nextcloud version:** 20

<details>
<summary>List of activated apps</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.2
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.3
  - user_oidc: 2.0.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - workflowengine: 2.2.1
Disabled:
  - contactsinteraction
  - encryption
  - theming
  - weather_status

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Browser

**Browser name:** Firefox

**Browser version:** 132.0.1 (64-bit)

**Operating system:** Ubuntu

**Comment by janepie** [comment]
Thank you for your report! You are running Nextcloud 20 which is not maintained anymore. This app is only supported for versions >= 26.
If the problem still persists for you after an update, please provide more information about your provider configuration.
