### ISSUE TITLE
Configure user provisioning through the bearer token with the occ command

### ISSUE THREAD

**Issue by bdovaz** [nextcloud/user_oidc#985]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** (see administration page)

30.0.2

**Is your feature request related to a problem? Please describe.**

In the command to create or update a provider, the “Auto provision user when accessing API and WebDav with Bearer token” option cannot be configured.

https://github.com/nextcloud/user_oidc/blob/main/lib/Command/UpsertProvider.php#L30

**Describe the solution you'd like**

That it can be configured through the command.

**Describe alternatives you've considered**

Using **config:app:set** command: https://docs.nextcloud.com/server/latest/admin_manual/occ_command.html#config-commands

Seeing that this API is used in this service (config->get/setAppValue): https://github.com/nextcloud/user_oidc/blob/main/lib/Service/ProviderService.php

**Additional context**

I don't know if there are more such inconsistencies, in the sense that there are options in the UI that are not configurable with the command provided by this app without having to use **config:app:set** generic command.

**Comment by bdovaz** [comment]
@julien-nc I have waited a week, but seeing that there is no response to this issue.


Would you be willing to accept a PR? Thanks!

**Comment by julien-nc** [comment]
PRs for this are welcome, yes.
